{
    "name": "Discuss - Livekit Integration",
    "summary": "Integrate LiveKit video conferencing with Odoo Discuss",
    "version": "18.0.1.0.0",
    "author": "Odoo Community Association (OCA), Solvti Sp. z o.o.",
    "license": "LGPL-3",
    "category": "Discuss",
    "depends": ["mail"],
    "website": "https://www.solvti.com",
    "data": [
        "security/ir.model.access.csv",
        "data/ir_cron.xml",
        "views/res_config_settings_views.xml",
        "views/livekit_assets_templates.xml",
    ],
    "assets": {
        "mail_livekit.assets_livekit": [
            "mail_livekit/static/lib/bundles/livekit_vendor_entry.js",
            "mail_livekit/static/src/discuss/livekit/livekit_camera_manager.js",
            "mail_livekit/static/src/discuss/livekit/livekit_microphone_manager.js",
            "mail_livekit/static/src/discuss/livekit/livekit_cross_tab_coordinator.js",
            "mail_livekit/static/src/discuss/livekit/livekit_presence_service.js",
            "mail_livekit/static/src/discuss/livekit/livekit_room_manager.js",
            "mail_livekit/static/src/discuss/livekit/livekit_screen_share_manager.js",
            "mail_livekit/static/src/discuss/livekit/livekit_sdk_loader.js",
            "mail_livekit/static/src/discuss/livekit/livekit_service.js",
            "mail_livekit/static/src/discuss/livekit/livekit_utils.js",
            "mail_livekit/static/src/discuss/call_participant_video_livekit_patch.js",
            "mail_livekit/static/src/discuss/livekit_rtc_adapter_service.js",
            "mail_livekit/static/src/discuss/rtc_livekit_patch.js",
        ],
    },
    "external_dependencies": {
        "python": ["livekit-api"],
    },
    "reusable": False,
    "installable": True,
    "application": False,
    "auto_install": False,
}
