[options]
admin_passwd = odoo
db_host = postgres
db_port = 5432
db_user = odoo
db_password = odoo
db_name = nitrokey
http_port = 8069
gevent_port = 8072
data_dir = /code/data
addons_path =
    /code/odoo/addons,
    /code/enterprise,
    /code/design-themes,
    /code/repos/nitrokey,
list_db = False
limit_time_real = 2000
limit_time_cpu = 2000
#dev_mode = True
#server_wide_modules = web,queue_job
# workers = 2
# proxy_mode = True

# [queue_job]
# channels = root:2
