{
    "name": "Bitcoin Payment Acquirer",
    "category": "Hidden",
    "summary": "Payment Acquirer: Bitcoin Transfer Implementation",
    "version": "18.0.1.0.0",
    "author": "Nitrokey GmbH, Odoo Community Association (OCA)",
    "website": "https://github.com/OCA/server-tools",
    "license": "LGPL-3",
    "depends": ["payment", "website_sale", "base_automation", "account"],
    "data": [
        "security/ir.model.access.csv",
        "views/bitcoin_views.xml",
        "views/payment_bitcoin_templates.xml",
        "views/counter_qweb.xml",
        "views/cart.xml",
        "views/res_config_settings_view.xml",
        "views/payment_provider.xml",
        "views/sale_portal_view.xml",
        "data/base_automation_data.xml",
        "data/mail_template_data.xml",
        "data/ir_cron_data.xml",
        "data/payment_provider_data.xml",
    ],
    "assets": {
        "web.assets_frontend": [
            "payment_bitcoin/static/src/js/bitcoin.js",
            "payment_bitcoin/static/src/js/countdown.js",
            "payment_bitcoin/static/src/css/bitcoin_custom.css",
        ],
    },
    "installable": True,
    "auto_install": False,
}
