=========================
Bitcoin Payment Acquirer
=========================

.. !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
   !! This file is generated by oca-gen-addon-readme !!
   !! changes will be overwritten.                   !!
   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

.. |badge1| image:: https://img.shields.io/badge/maturity-Beta-yellow.png
    :target: https://odoo-community.org/page/development-status
    :alt: Beta
.. |badge2| image:: https://img.shields.io/badge/licence-LGPL--3-blue.png
    :target: http://www.gnu.org/licenses/lgpl-3.0-standalone.html
    :alt: License: LGPL-3
.. |badge3| image:: https://img.shields.io/badge/github-OCA%2Fserver--tools-lightgray.png?logo=github
    :target: https://github.com/OCA/server-tools/tree/18.0/payment_bitcoin
    :alt: OCA/server-tools

|badge1| |badge2| |badge3|

This module implements a Bitcoin payment acquirer for Odoo, allowing customers to pay for their orders using Bitcoin cryptocurrency.

**Features:**

* Accept Bitcoin payments in e-commerce and sales orders
* Automatic Bitcoin address generation and management
* Real-time Bitcoin rate fetching from external APIs
* Configurable markup for Bitcoin exchange rates
* Payment expiration countdown timer
* Automatic order confirmation upon Bitcoin payment receipt
* Integration with Odoo's payment workflow
* Portal view for customers to see Bitcoin payment instructions

**Table of contents**

.. contents::
   :local:

Configuration
=============

1. Go to **Accounting → Configuration → Payment Providers**
2. Find or create the Bitcoin payment provider
3. Configure the following settings:

   * **Bitcoin Rate URL**: API endpoint to fetch current Bitcoin rates
   * **Markup**: Percentage markup to add to the Bitcoin rate (e.g., 5 for 5%)
   * **Digits**: Number of decimal places for Bitcoin amounts
   * **Unit**: Bitcoin unit to use (BTC, mBTC, satoshi, etc.)
   * **Valid Minutes**: How long a payment quote remains valid

4. Go to **Accounting → Configuration → Bitcoin Addresses** to manage Bitcoin addresses

   * Add Bitcoin addresses that will be used for receiving payments
   * Addresses are automatically assigned to orders when customers choose Bitcoin payment

Usage
=====

For Customers
-------------

1. During checkout, select **Bitcoin** as the payment method
2. After order confirmation, you'll see:

   * The Bitcoin address to send payment to
   * The exact amount to pay in Bitcoin
   * A countdown timer showing how long the rate is valid
   * A QR code for easy mobile payment

3. Send the exact Bitcoin amount to the provided address
4. The order will be automatically confirmed once payment is received

For Administrators
------------------

* Monitor Bitcoin addresses and their assignments in **Accounting → Configuration → Bitcoin Addresses**
* View Bitcoin rate history in **Accounting → Configuration → Bitcoin Rate**
* Payment transactions are automatically created and tracked in the standard Odoo payment workflow
* Configure automated actions for payment confirmation in **Settings → Technical → Automation → Automated Actions**
